version: '3.8'

services:
  app:
    build: ./
    ports:
      - "3019:80"
    restart: always
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - /filestoragestalento:/filestoragestalento
